[app]
name = "expense-splitter"

[env]
PORT = "8000"

[database]
name = "postgres"
size = "free"

[build]
command = "pip install -r requirements.txt"

[start]
command = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
